# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/neuro-meeglet',
                'doc_host': 'https://Roche.github.io',
                'git_url': 'https://github.com/Roche/neuro-meeglet',
                'lib_path': 'meeglet'},
  'syms': {}}
